language: python

sudo: false

matrix:
  include:
    - python: 3.5
      env: TOX_ENV='flake8'
    # Django 1.11
    - python: 3.5
      env: DJANGO='dj111' CMS='cms34'
    - python: 3.5
      env: DJANGO='dj111' CMS='cms35'
    - python: 3.5
      env: DJANGO='dj111' CMS='cms36'
    - python: 3.5
      env: DJANGO='dj111' CMS='cms40'

    - python: 3.4
      env: DJANGO='dj111' CMS='cms34'
    - python: 3.4
      env: DJANGO='dj111' CMS='cms35'
    - python: 3.4
      env: DJANGO='dj111' CMS='cms36'
    - python: 3.4
      env: DJANGO='dj111' CMS='cms40'

    - python: 2.7
      env: DJANGO='dj111' CMS='cms34'
    - python: 2.7
      env: DJANGO='dj111' CMS='cms35'
    - python: 2.7
      env: DJANGO='dj111' CMS='cms36'
    - python: 2.7
      env: DJANGO='dj111' CMS='cms40'
    # Django 2.0
    - python: 3.4
      env: DJANGO='dj20' CMS='cms36'
    - python: 3.5
      env: DJANGO='dj20' CMS='cms36'
    - python: 3.6
      env: DJANGO='dj20' CMS='cms36'
    - python: 3.4
      env: DJANGO='dj20' CMS='cms40'
    - python: 3.5
      env: DJANGO='dj20' CMS='cms40'
    - python: 3.6
      env: DJANGO='dj20' CMS='cms40'
    # Django 2.1
    - python: 3.5
      env: DJANGO='dj21' CMS='cms36'
    - python: 3.6
      env: DJANGO='dj21' CMS='cms36'
    - python: 3.5
      env: DJANGO='dj21' CMS='cms40'
    - python: 3.6
      env: DJANGO='dj21' CMS='cms40'

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox coveralls
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PY_VER=py27; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then export PY_VER=py34; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PY_VER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PY_VER=py36; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOX_ENV=$PY_VER-$DJANGO-$CMS; fi"

script:
  - tox -e $TOX_ENV

after_script:
  - codeclimate < tests/coverage/**/lcov.info

after_success: coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
