# Generated by Django 2.1.5 on 2019-04-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_notifications', '0004_auto_20190104_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='reply_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='reply email'),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='reply_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='reply name'),
        ),
    ]
