# Generated by Django 3.1.4 on 2021-11-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_notifications', '0005_add_field_reply_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='is_use_in_condition',
            field=models.BooleanField(default=False, help_text='This email notification will be used if condition field for the form is the same as condition value (See Form plugin configuration -> Condition Logic)', verbose_name='Use if condition succeeded'),
        ),
    ]
