# Generated by Django 3.2 on 2023-11-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_notifications', '0006_alter_emailnotification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='files_to_attach_to_email',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of file fields that should be attached directly to the email.', max_length=255, verbose_name='Files to attach to the email'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
