# Generated by Django 3.2.17 on 2024-03-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_notifications', '0006_emailnotification_is_use_in_condition'),
        ('email_notifications', '0007_auto_20231105_0323'),
    ]

    operations = [
    ]
