# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-13 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0008_auto_20170316_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='formplugin',
            name='email_only',
            field=models.BooleanField(default=False, help_text='If checked the submitted forms will NOT persist on database - only the emails will be sent.', verbose_name='"Email only" mode'),
        ),
    ]
