# Generated by Django 2.2.7 on 2019-12-10 08:20

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0012_auto_20190104_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formplugin',
            name='action_backend',
            field=models.CharField(choices=[('email_only', 'Email only'), ('none', 'None'), ('default', 'Default')], default='default', max_length=15, verbose_name='Action backend'),
        ),
        migrations.AlterField(
            model_name='formplugin',
            name='error_message',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text="An error message that will be displayed if the form doesn't validate.", null=True, verbose_name='Error message'),
        ),
        migrations.AlterField(
            model_name='formplugin',
            name='success_message',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='An success message that will be displayed.', null=True, verbose_name='Success message'),
        ),
    ]
