# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-22 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0012_auto_20190104_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='formplugin',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL that will receive the submitted form data.', verbose_name='Webhook url'),
        ),
        migrations.AlterField(
            model_name='formplugin',
            name='action_backend',
            field=models.CharField(choices=[('none', 'None'), ('email_only', 'Email only'), ('default', 'Default'), ('webhook_only', 'Webhook')], default='default', max_length=15, verbose_name='Action backend'),
        ),
    ]
