# Generated by Django 2.1.5 on 2019-04-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0012_auto_20190104_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formplugin',
            name='action_backend',
            field=models.CharField(choices=[('none', 'None'), ('default', 'Default'), ('email_only', 'Email only')], default='default', max_length=15, verbose_name='Action backend'),
        ),
    ]
