# Generated by Django 3.2 on 2023-11-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0014_alter_emailfieldplugin_cmsplugin_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadfieldplugin',
            name='allowed_extensions',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of file extensions allowed for this file field.', max_length=255, verbose_name='Allowed extensions'),
        ),
        migrations.AddField(
            model_name='imageuploadfieldplugin',
            name='allowed_extensions',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of file extensions allowed for this file field.', max_length=255, verbose_name='Allowed extensions'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='option',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
