# Generated by Django 3.2 on 2023-11-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0015_auto_20231105_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadfieldplugin',
            name='store_to_filer',
            field=models.BooleanField(default=True, help_text='Whether to store this file to filer. If this is unchecked and this file is not attached to any email notification, the file will be lost forever and using it as a template variable in any email template will return empty result.', verbose_name='Store this file to filer'),
        ),
        migrations.AddField(
            model_name='imageuploadfieldplugin',
            name='store_to_filer',
            field=models.BooleanField(default=True, help_text='Whether to store this file to filer. If this is unchecked and this file is not attached to any email notification, the file will be lost forever and using it as a template variable in any email template will return empty result.', verbose_name='Store this file to filer'),
        ),
        migrations.AlterField(
            model_name='fileuploadfieldplugin',
            name='allowed_extensions',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of file extensions allowed for this file field. Leave it empty to allow any extension.', max_length=255, verbose_name='Allowed extensions'),
        ),
        migrations.AlterField(
            model_name='imageuploadfieldplugin',
            name='allowed_extensions',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of file extensions allowed for this file field. Leave it empty to allow any extension.', max_length=255, verbose_name='Allowed extensions'),
        ),
    ]
