# Generated by Django 3.2 on 2023-11-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0016_auto_20231108_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadfieldplugin',
            name='invalid_extension_message',
            field=models.TextField(blank=True, help_text='Error message displayed if extensions are constrained and the uploaded file fails that validation.Default: "File extension [extension] is not allowed for this field."', null=True, verbose_name='Invalid extension error message'),
        ),
        migrations.AddField(
            model_name='imageuploadfieldplugin',
            name='invalid_extension_message',
            field=models.TextField(blank=True, help_text='Error message displayed if extensions are constrained and the uploaded file fails that validation.Default: "File extension [extension] is not allowed for this field."', null=True, verbose_name='Invalid extension error message'),
        ),
        migrations.AlterField(
            model_name='emailfieldplugin',
            name='required_message',
            field=models.TextField(blank=True, help_text='Error message displayed if the required field is left empty. Default: "This field is required".', null=True, verbose_name='Field required error message'),
        ),
        migrations.AlterField(
            model_name='fieldplugin',
            name='required_message',
            field=models.TextField(blank=True, help_text='Error message displayed if the required field is left empty. Default: "This field is required".', null=True, verbose_name='Field required error message'),
        ),
        migrations.AlterField(
            model_name='fileuploadfieldplugin',
            name='required_message',
            field=models.TextField(blank=True, help_text='Error message displayed if the required field is left empty. Default: "This field is required".', null=True, verbose_name='Field required error message'),
        ),
        migrations.AlterField(
            model_name='imageuploadfieldplugin',
            name='required_message',
            field=models.TextField(blank=True, help_text='Error message displayed if the required field is left empty. Default: "This field is required".', null=True, verbose_name='Field required error message'),
        ),
        migrations.AlterField(
            model_name='textareafieldplugin',
            name='required_message',
            field=models.TextField(blank=True, help_text='Error message displayed if the required field is left empty. Default: "This field is required".', null=True, verbose_name='Field required error message'),
        ),
    ]
