# Generated by Django 3.2.17 on 2024-03-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0015_auto_20211117_1202'),
        ('aldryn_forms', '0017_auto_20231113_1824'),
    ]

    operations = [
    ]
